FROM python:3.11-slim-bullseye
LABEL authors="nirkon"

WORKDIR /app

COPY llm/. /app/llm
COPY prompts/. /app/prompts
COPY queues/. /app/queues
COPY templates/. /app/templates
COPY util/. /app/util
COPY llm_queue_server.py /app/llm__queue_server.py
COPY llm_stream_server.py /app/llm_stream_server.py
COPY message_queue_config.yaml /app/message_queue_config.yaml
COPY requirements.txt /app/requirements.txt

# Updating apt and installing build essentials before installing Python dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir -r requirements.txt \
    # Cleaning up to reduce image size
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.cache/pip/*

EXPOSE 8081

CMD ["uvicorn", "llm_stream_server:app", "--host", "0.0.0.0", "--port", "8081"]